# Generated by Django 5.2.17 on 2026-08-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('coe', 'coe'), ('superintendent', 'superintendent'), ('student', 'student')], default='teacher', max_length=20),
        ),
    ]
