# Generated by Django 5.2.17 on 2026-08-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='access_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalpapers',
            name='access_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalpapers',
            name='exam_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='selection_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('SELECTED', 'Selected'), ('NOT_SELECTED', 'Not Selected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
