# Generated by Django 5.2.17 on 2026-09-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_finalpapers_access_end_finalpapers_access_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='encrypted_cid',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
