# Generated by Django 5.2.17 on 2026-09-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_add_encrypted_cid_to_finalpapers'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalpapers',
            name='wrapped_ct',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='finalpapers',
            name='wrapped_iv',
            field=models.TextField(blank=True, default=''),
        ),
    ]
