# Generated by Django 5.2.17 on 2026-09-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_add_key_wrapping_fields_to_finalpapers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_username', models.CharField(db_index=True, max_length=150)),
                ('actor_role', models.CharField(db_index=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('paper_id', models.IntegerField(blank=True, null=True)),
                ('s_code', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=10)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['action', '-timestamp'], name='exams_audit_action_e765d1_idx'), models.Index(fields=['s_code', '-timestamp'], name='exams_audit_s_code_1f7b9b_idx'), models.Index(fields=['severity', '-timestamp'], name='exams_audit_severit_d2bd34_idx')],
            },
        ),
    ]
